import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <Link href="/">홈</Link>
            <Link href="/members">회원목록</Link>
            <Link href="/bbs">게시판</Link>
          </nav>
          <div className="fr">
            <Link href="/members/signin">로그인</Link>
            <Link href="/members/signup">회원가입</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
